version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - STATE_PATH=/data/state
      - PROJECTS_PATH=/data/projects
      - FILE_ROOT=/workspace
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      # Persistent state storage
      - coding-agent-state:/data/state
      # Projects directory for code execution
      - ${PROJECTS_PATH:-./projects}:/data/projects
      # Mount local workspace for file operations
      - ${HOST_FILE_ROOT:-/var/www/html/systemprompt-coding-agent}:/workspace:rw
      # Docker socket for container management (optional)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    network_mode: "host"
    depends_on:
      - mcp-server
    restart: unless-stopped

volumes:
  coding-agent-state:
    name: coding-agent-state
    driver: local
