/**
 * @file Prompts index - aggregates all coding prompts
 * @module handlers/prompts
 */

// Unit Testing Prompts
export {
  CREATE_UNIT_TESTS_PROMPT,
  ADD_MISSING_TESTS_PROMPT,
  FIX_FAILING_TESTS_PROMPT,
  TEST_COVERAGE_IMPROVEMENT_PROMPT
} from './unit-testing.js';

// React Component Prompts
export {
  CREATE_REACT_COMPONENT_PROMPT,
  UPDATE_REACT_COMPONENT_PROMPT,
  CONVERT_TO_HOOKS_PROMPT,
  CREATE_CUSTOM_HOOK_PROMPT,
  OPTIMIZE_REACT_PERFORMANCE_PROMPT
} from './react-components.js';

// Bug Fixing Prompts
export {
  FIX_BUG_PROMPT,
  DEBUG_ASYNC_ISSUE_PROMPT,
  FIX_MEMORY_LEAK_PROMPT,
  DEBUG_PRODUCTION_ISSUE_PROMPT,
  FIX_PERFORMANCE_ISSUE_PROMPT
} from './bug-fixing.js';

// Refactoring Prompts
export {
  REFACTOR_CODE_PROMPT,
  EXTRACT_COMMON_CODE_PROMPT,
  SIMPLIFY_COMPLEX_FUNCTION_PROMPT,
  MODERNIZE_LEGACY_CODE_PROMPT,
  IMPROVE_CODE_ARCHITECTURE_PROMPT
} from './refactoring.js';

// Aggregate all prompts
import { CREATE_UNIT_TESTS_PROMPT, ADD_MISSING_TESTS_PROMPT, FIX_FAILING_TESTS_PROMPT, TEST_COVERAGE_IMPROVEMENT_PROMPT } from './unit-testing.js';
import { CREATE_REACT_COMPONENT_PROMPT, UPDATE_REACT_COMPONENT_PROMPT, CONVERT_TO_HOOKS_PROMPT, CREATE_CUSTOM_HOOK_PROMPT, OPTIMIZE_REACT_PERFORMANCE_PROMPT } from './react-components.js';
import { FIX_BUG_PROMPT, DEBUG_ASYNC_ISSUE_PROMPT, FIX_MEMORY_LEAK_PROMPT, DEBUG_PRODUCTION_ISSUE_PROMPT, FIX_PERFORMANCE_ISSUE_PROMPT } from './bug-fixing.js';
import { REFACTOR_CODE_PROMPT, EXTRACT_COMMON_CODE_PROMPT, SIMPLIFY_COMPLEX_FUNCTION_PROMPT, MODERNIZE_LEGACY_CODE_PROMPT, IMPROVE_CODE_ARCHITECTURE_PROMPT } from './refactoring.js';

export const CODING_PROMPTS = [
  // Unit Testing
  CREATE_UNIT_TESTS_PROMPT,
  ADD_MISSING_TESTS_PROMPT,
  FIX_FAILING_TESTS_PROMPT,
  TEST_COVERAGE_IMPROVEMENT_PROMPT,
  
  // React Components
  CREATE_REACT_COMPONENT_PROMPT,
  UPDATE_REACT_COMPONENT_PROMPT,
  CONVERT_TO_HOOKS_PROMPT,
  CREATE_CUSTOM_HOOK_PROMPT,
  OPTIMIZE_REACT_PERFORMANCE_PROMPT,
  
  // Bug Fixing
  FIX_BUG_PROMPT,
  DEBUG_ASYNC_ISSUE_PROMPT,
  FIX_MEMORY_LEAK_PROMPT,
  DEBUG_PRODUCTION_ISSUE_PROMPT,
  FIX_PERFORMANCE_ISSUE_PROMPT,
  
  // Refactoring
  REFACTOR_CODE_PROMPT,
  EXTRACT_COMMON_CODE_PROMPT,
  SIMPLIFY_COMPLEX_FUNCTION_PROMPT,
  MODERNIZE_LEGACY_CODE_PROMPT,
  IMPROVE_CODE_ARCHITECTURE_PROMPT
];